// @ts-expect-error Node types are supplied by the supported Node runtime.
import assert from "node:assert/strict";
// @ts-expect-error Node types are supplied by the supported Node runtime.
import test from "node:test";
import { defineResource, type StableKey } from "../../ecs/src/index.js";
import { RuntimeError, defineCapability, defineModule, provide, type ModuleDefinition, type Stage } from "../../module-api/src/index.js";
import { createRuntime } from "./index.js";

const sk = (value: string) => value as StableKey;
const module = (key: string, systems: ModuleDefinition["systems"] = [], extra: Partial<Omit<ModuleDefinition, "key" | "systems">> = {}) => defineModule({ key, requires: extra.requires ?? [], provides: extra.provides ?? [], systems, ...(extra.start === undefined ? {} : { start: extra.start }), ...(extra.stop === undefined ? {} : { stop: extra.stop }) });
const system = (key: string, stage: Stage, run: () => void, order: { before?: readonly StableKey[]; after?: readonly StableKey[] } = {}) => ({ key: sk(key), stage, reads: [], writes: [], run, ...order });

test("fixed-step schedule is independent of registration order", async () => { for (const modules of [[module("z", [system("z", "simulate", () => log.push("z"))]), module("a", [system("a", "simulate", () => log.push("a"))])], [module("a", [system("a", "simulate", () => log.push("a"))]), module("z", [system("z", "simulate", () => log.push("z"))])]]) { var log: string[] = []; const runtime = createRuntime({ clock: { stepSeconds: .5 }, modules }); await runtime.start(); assert.equal(runtime.advance(1.2), 2); assert.deepEqual(log, ["a", "z", "a", "z"]); assert.ok(Math.abs(runtime.interpolationAlpha - .4) < 1e-12); } });
test("explicit ordering and schedule diagnostics are stable", () => { const log: string[] = []; const a = module("m", [system("a", "simulate", () => log.push("a"), { after: [sk("b")] }), system("b", "simulate", () => log.push("b"))]); const runtime = createRuntime({ clock: { stepSeconds: 1 }, modules: [a] }); assert.ok(runtime); assert.throws(() => createRuntime({ clock: { stepSeconds: 1 }, modules: [module("x", [system("x", "simulate", () => {}, { before: [sk("gone")] })])] }), (e: unknown) => e instanceof RuntimeError && e.diagnostic.code === "SYSTEM_REFERENCE_MISSING"); assert.throws(() => createRuntime({ clock: { stepSeconds: 1 }, modules: [module("x", [system("x", "simulate", () => {}, { before: [sk("y")] }), system("y", "simulate", () => {}, { before: [sk("x")] })])] }), (e: unknown) => e instanceof RuntimeError && e.diagnostic.code === "SYSTEM_CYCLE"); });
test("capability factories are lazy, scoped, ordered, and delayed", async () => { let runtimeCalls = 0, moduleCalls = 0; const shared = defineCapability<number>({ key: "shared", multiplicity: "collection", requirement: "required", scope: "runtime" }); const local = defineCapability<object>({ key: "local", multiplicity: "single", requirement: "required", scope: "module" }); const delayed = defineCapability<number>({ key: "delayed", multiplicity: "single", requirement: "required", scope: "runtime" }); const seen: unknown[] = []; const provider = module("provider", [], { provides: [provide(shared, "z", () => ++runtimeCalls), provide(shared, "a", 1), provide(local, "local-provider", () => ({ call: ++moduleCalls })), provide(delayed, "late", () => 9, { delayed: true })] }); const consumer = (key: string) => module(key, [], { requires: [shared, local, delayed], start(ctx) { seen.push(ctx.resolve(shared), ctx.resolve(local), ctx.resolve(delayed)); } }); const runtime = createRuntime({ clock: { stepSeconds: 1 }, modules: [consumer("c2"), provider, consumer("c1")] }); assert.equal(runtimeCalls, 0); await runtime.start(); assert.equal(runtimeCalls, 1); assert.equal(moduleCalls, 2); assert.deepEqual(seen[0], [1, 1]); assert.equal(seen[2], 9); assert.notEqual(seen[1], seen[4]); });
test("start and stop preserve in-flight promise identity and reverse cleanup", async () => { const order: string[] = []; const a = module("a", [], { start() { order.push("start-a"); }, stop() { order.push("stop-a"); } }); const b = module("b", [], { start() { order.push("start-b"); }, stop() { order.push("stop-b"); } }); const runtime = createRuntime({ clock: { stepSeconds: 1 }, modules: [b, a] }); const p = runtime.start(); assert.equal(runtime.start(), p); await p; const q = runtime.stop(); assert.equal(runtime.stop(), q); await q; assert.deepEqual(order, ["start-a", "start-b", "stop-b", "stop-a"]); });
test("startup failure cleans completed modules", async () => { const order: string[] = []; const runtime = createRuntime({ clock: { stepSeconds: 1 }, modules: [module("a", [], { start() { order.push("start-a"); }, stop() { order.push("stop-a"); } }), module("b", [], { start() { throw new Error("boom"); } })] }); await assert.rejects(runtime.start(), (e: unknown) => e instanceof RuntimeError && e.diagnostic.code === "MODULE_START_FAILED"); assert.equal(runtime.state, "failed"); assert.deepEqual(order, ["start-a", "stop-a"]); });
test("stop during startup cancels and cleans up", async () => { let release!: () => void; const gate = new Promise<void>((resolve) => { release = resolve; }); const order: string[] = []; const runtime = createRuntime({ clock: { stepSeconds: 1 }, modules: [module("a", [], { async start() { order.push("start"); await gate; }, stop() { order.push("stop"); } }), module("b", [], { start() { order.push("forbidden"); } })] }); const start = runtime.start(); const stop = runtime.stop(); release(); await Promise.all([start, stop]); assert.equal(runtime.state, "stopped"); assert.deepEqual(order, ["start", "stop"]); });
test("stage writes commit atomically on conflict", async () => { const value = defineResource<number>("value"); const seed = module("seed", [{ key: sk("seed"), stage: "collect", reads: [], writes: [value.key], run(ctx) { ctx.write(value, 1); } }]); const conflict = module("conflict", [{ key: sk("left"), stage: "simulate", reads: [], writes: [value.key], run(ctx) { ctx.write(value, 2); } }, { key: sk("right"), stage: "simulate", reads: [], writes: [value.key], run(ctx) { ctx.write(value, 3); } }]); const runtime = createRuntime({ clock: { stepSeconds: 1 }, modules: [conflict, seed] }); await runtime.start(); assert.throws(() => runtime.tick(), /COMMIT_CONFLICT/); assert.equal(runtime.world.getResource(value), 1); });
