// @ts-expect-error Node types are supplied by the supported Node runtime.
import assert from "node:assert/strict";
// @ts-expect-error Node types are supplied by the supported Node runtime.
import test from "node:test";
import { defineCapability, defineModule, provide, resolveCapability, resolveModuleGraph } from "./index.js";

const module = (key: string, requires: readonly ReturnType<typeof defineCapability<unknown>>[] = [], provides: readonly ReturnType<typeof provide<unknown>>[] = []) => defineModule({ key, requires, provides, systems: [] });
test("constructors freeze definitions and preserve delayed factories", () => { const token = defineCapability<number>({ key: "number", multiplicity: "single", requirement: "required", scope: "runtime" }); let calls = 0; const provider = provide(token, "number-provider", () => ++calls, { delayed: true }); const definition = module("provider", [], [provider]); assert.equal(Object.isFrozen(token) && Object.isFrozen(provider) && Object.isFrozen(definition), true); resolveModuleGraph([definition]); assert.equal(calls, 0); });
test("ordering and collection resolution are registration-order invariant", () => { const token = defineCapability<number>({ key: "numbers", multiplicity: "collection", requirement: "required", scope: "module" }); const a = module("a", [], [provide(token, "z", 2), provide(token, "a", 1)]); const consumer = module("consumer", [token]); for (const input of [[consumer, a], [a, consumer]]) { const graph = resolveModuleGraph(input); assert.deepEqual(graph.modules.map((item) => item.key), ["a", "consumer"]); const resolved = resolveCapability(graph, token) as readonly ReturnType<typeof provide<number>>[]; assert.deepEqual(resolved.map((item) => item.key), ["a", "z"]); } });
test("optional zero-provider table entries resolve explicitly", () => { const single = defineCapability<number>({ key: "one", multiplicity: "single", requirement: "optional", scope: "runtime" }); const collection = defineCapability<number>({ key: "many", multiplicity: "collection", requirement: "optional", scope: "runtime" }); const graph = resolveModuleGraph([module("consumer", [single, collection])]); assert.equal(resolveCapability(graph, single), undefined); assert.deepEqual(resolveCapability(graph, collection), []); assert.deepEqual(graph.diagnostics, []); });
test("missing and ambiguous capabilities are fatal and stable", () => { const missing = defineCapability<number>({ key: "missing", multiplicity: "single", requirement: "required", scope: "runtime" }); const ambiguous = defineCapability<number>({ key: "ambiguous", multiplicity: "single", requirement: "optional", scope: "runtime" }); const graph = resolveModuleGraph([module("consumer", [missing, ambiguous]), module("b", [], [provide(ambiguous, "p2", 2)]), module("a", [], [provide(ambiguous, "p1", 1)])]); assert.deepEqual(graph.diagnostics.map((item) => item.code), ["CAPABILITY_AMBIGUOUS", "CAPABILITY_MISSING"]); assert.deepEqual(graph.diagnostics[0]?.relatedKeys, ["ambiguous", "consumer", "p1", "p2"]); });
test("duplicate module and provider keys are diagnosed", () => { const token = defineCapability<number>({ key: "value", multiplicity: "collection", requirement: "optional", scope: "runtime" }); const graph = resolveModuleGraph([module("same"), module("same"), module("x", [], [provide(token, "provider", 1)]), module("y", [], [provide(token, "provider", 2)])]); assert.deepEqual(graph.diagnostics.map((item) => item.code), ["MODULE_DUPLICATE", "PROVIDER_DUPLICATE"]); });
test("cycles report all participating stable keys", () => { const aToken = defineCapability<number>({ key: "a-token", multiplicity: "single", requirement: "required", scope: "runtime" }); const bToken = defineCapability<number>({ key: "b-token", multiplicity: "single", requirement: "required", scope: "runtime" }); const a = module("a", [bToken], [provide(aToken, "a-provider", 1)]); const b = module("b", [aToken], [provide(bToken, "b-provider", 2)]); const graph = resolveModuleGraph([b, a]); assert.deepEqual(graph.diagnostics.map((item) => item.code), ["MODULE_CYCLE"]); assert.deepEqual(graph.diagnostics[0]?.relatedKeys, ["a", "b"]); });
